.TH px 1 2012-06-06

.SH NAME
px \- examinates an running process

.SH SYNOPSIS
.B px
.RB "[\|" \--help "\|]"
.RB "[\|" \--version "\|]"

.SH DESCRIPTION
The purpose of this program is to allow you to examine a running process
via an interactive prompt.

.SH OPTIONS
When using the prompt, the following commands are available:

.B attach <pid>\c
\& \- attaches to an specified pid

.B detach\c
\& \- detaches from an attached pid

.B maps\c
\& \- maps the memory using the /proc/<pid>/maps information

.B find <address>\c
\& \- finds an address in a mapped regions

.B show <sections|segments|auxv>\c
\& \- displays information related to the ELF target

.B quit\c
\& \- exits from the prompt

.SH COPYING

BSD License.
